os: linux
language: python
services:
  - docker
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
addons:
  apt:
    packages:
    - exuberant-ctags
jobs:
  include:
    - python: 3.7
      dist: xenial

install:
  - "pip install ."
  - "pip install -r test_requirements.txt"
script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - ./runtests.sh
deploy:
  provider: script
  on:
    tags: true
  script: ./build-and-push-docker.sh
